import googleImage from '../res/images/google.png'

export const ImpactorData = [
    {
        "wallet": "fhlefhhiefhefhiehifhie",
        "name": "ChainImpact",
        "description": "Blockchain",
        "website": null,
        "facebook": null,
        "discord": null,
        "twitter": null,
        "instagram": null,
        "imageurl": null,
        "role": 1,
        "type": 0
    },
    {
        "wallet": "dsdawioawehfuioaweuogfaeuif",
        "name": "RedTech",
        "description": "Enterprise",
        "website": null,
        "facebook": null,
        "discord": null,
        "twitter": null,
        "instagram": null,
        "imageurl": null,
        "role": 1,
        "type": 0
    },
    {
        "wallet": "asfheuofhseuogfuiosegfuide",
        "name": "Decenter",
        "description": "Blockchain",
        "website": null,
        "facebook": null,
        "discord": null,
        "twitter": null,
        "instagram": null,
        "imageurl": null,
        "role": 1,
        "type": 0
    },
    {
        "wallet": "sgsgsgghuuhu",
        "name": "MintAI",
        "description": "Blockchain x2",
        "website": null,
        "facebook": null,
        "discord": null,
        "twitter": null,
        "instagram": null,
        "imageurl": null,
        "role": 1,
        "type": 0
    },
    {
        "wallet": "fjasdhfuideg",
        "name": "Facebook",
        "description": "Software",
        "website": null,
        "facebook": null,
        "discord": null,
        "twitter": null,
        "instagram": null,
        "imageurl": null,
        "role": 1,
        "type": 0
    },
    {
        "wallet": "gggfdgnkd",
        "name": "Google",
        "description": "Software",
        "website": null,
        "facebook": null,
        "discord": null,
        "twitter": null,
        "instagram": null,
        "imageurl": googleImage,
        "role": 1,
        "type": 0
    },
    {
        "wallet": "ghsdrgegt",
        "name": "mdodovic",
        "description": "DB admin",
        "website": null,
        "facebook": null,
        "discord": null,
        "twitter": null,
        "instagram": null,
        "imageurl": null,
        "role": 1,
        "type": 1
    },
    {
        "wallet": "gsdggf",
        "name": "limun",
        "description": "unrealist",
        "website": null,
        "facebook": null,
        "discord": null,
        "twitter": null,
        "instagram": null,
        "imageurl": null,
        "role": 1,
        "type": 1
    },
    {
        "wallet": "fawefefe",
        "name": "kismeta",
        "description": "dlu",
        "website": null,
        "facebook": null,
        "discord": null,
        "twitter": null,
        "instagram": null,
        "imageurl": null,
        "role": 1,
        "type": 1
    },
    {
        "wallet": "aaaaaaaaaaaaaaaaaaaaaa",
        "name": "georg redtech",
        "description": "manager",
        "website": null,
        "facebook": null,
        "discord": null,
        "twitter": null,
        "instagram": null,
        "imageurl": null,
        "role": 1,
        "type": 1
    }
]